SatanicLib:
  debugger: false #показывает некоторую информацию тем, у кого есть ОП. Пока тестируете плагин можно его включить
global:
  customEnchantChance: 0.4 #Шанс на то, что игрок при зачаровании на столе для зачарований получит 40% шанс того, что выпадет КАКОЕ-ЛИБО кастомное зачарование, по мимо основного)
  levels: #Хекс формат &#80461b #Поддерживает цвет + PAPI
    1: "I"
    2: "II"
    3: "III"
    4: "IV"
    5: "V"
    6: "VI"
    7: "VII"
    8: "VIII"
    9: "IX"
    10: "X"
enchants:
  #Внимание. Проценты не абсолютные, а относительные, т.к используется несколько объектов.
  #Т.е если у какого-то зачара будет шанс на выпадение 1.0 (100%) то все равно есть шанс того, что выпадут и другие зачарования
  #"Настоящий" процент можно посчитать так:
  #Предположим, у нас есть 4 зачарования.
  # 1е имеет шанс 1.0 (100%)
  # 2е имеет шанс 0.4(40%)
  # 3е имеет шанс 0.2(20%)
  # 4е имеет шанс 0.35(35%)
  # Сумма всех шансов = 1.0 + 0.4 + 0.2 + 0.35 = 1.95
  # 1% от 1.95 = (1.95)/100 = 0,0195
  # Далее считаем интересующий нас шанс(например 1.0 (100%)): 1/0,0195 = 51%
  # Т.е примерно каждый 2й предмет будет зачарован на зачарование с таким шансом.
  # Что бы не считать каждый раз "настойщий" процент можно просто сделать сумму всех шансов у зачарований равным 1 (100%)
  # Тогда это сразу будет "настоящий процент"
  #
  autosmelt:
    displayname: "&7Автоплавка " #Хекс формат &#80461b #Поддерживает цвет + PAPI
    ItemEnchantChance: 0.2 #(Игрок при зачаровании получит 20% шанс того, что выпадет ИМЕННО ЭТО зачарование, по мимо основного)
  dozer:
    displayname: "&7Бульдозер "
    ItemEnchantChance: 0.2
  magnet:
    displayname: "&7Магнит "
    ItemEnchantChance: 0.2
  poison:
    displayname: "&7Ядовитый клинок "
    poisonTime: 200 #время на которое будет наложен яд в тиках. 200 тиков = 10 секунд
    damageModifier: 1 #это множитель для урона. Сейчас урон будет следующий: на 1м уровне 0.5, на 2м уровне 1 на 3м уровне 1.5. Если множитель урона 1 то ничего не меняется.
      #если множитель 1.5 то урон для каждого уровня будет 0,75 1.5 2.25 соответственно
      #P.S у игрока не 20 хп а 20.0000000
    triggerChance: 0.4 #Шанс отравить игрока
    ItemEnchantChance: 0.2
  vampire:
    displayname: "&7Вампиризм "
    triggerChance: 0.4 #40%
    percentOfDamage:
      1: 0.15 #15% от урона(на 1 уровне зачарования), который нанесет игрок(после просчета всех сопротивлений) будет восстановлено с шансом 40%
      2: 0.30 #30% от урона(на 2 уровне зачарования), который нанесет игрок(после просчета всех сопротивлений) будет восстановлено с шансом 40%
      3: 0.45 #45% от урона(на 3 уровне зачарования), который нанесет игрок(после просчета всех сопротивлений) будет восстановлено с шансом 40%
    ItemEnchantChance: 0.2